version: '3'
services:
  inventory-service:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"